# Pre-Commit for piotr
# ========================================================
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
# -   id: check-added-large-files
# -   repo: https://github.com/shellcheck-py/shellcheck-py
#     rev: v0.10.0.1
#     hooks:
#     -   id: shellcheck
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
    -   id: gitleaks
# -   repo: local
#     hooks:
#     -   id: trufflehog
#         name: TruffleHog
#         description: Detect secrets in your data.
#         entry: bash -c 'podman run --rm -v "$(pwd):/workdir" -i --rm docker.io/trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
#         language: system
#         stages: ["pre-commit", "pre-push"]
