[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
# [pyprland.variables]
# term_classed = "ghostty"

# [scratchpads.term]
# animation = "fromTop"
# command = "[term_classed] main-dropterm"
# class = "main-dropterm"
# size = "75% 60%"
# max_size = "1920px 100%"
